### ISSUE TITLE
The Query should return empty result rather than error if GraphQL query results in an empty result set

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-weaviate#4]
### Feature description

Example query:

```graphql
{
  Get {
    Question(limit: 50) {
      question
      answer
      category
    }
  }
}
```

![image](https://github.com/kestra-io/plugin-weaviate/assets/86264395/7b5e3188-f2c2-495d-af0f-6a69342a808b)

Flow reproducer:

```yaml
id: weaviate_query
namespace: dev

tasks:
  - id: query
    type: "io.kestra.plugin.weaviate.Query"
    host: https://demo-oczq9ryw.weaviate.network
    apiKey: xxxxx
    query: | 
      {
        Get {
          Question(limit: 50) {
            question
            answer
            category
          }
        }
      }
```

full stack trace:

```
Cannot invoke "io.weaviate.client.v1.graphql.model.GraphQLResponse.getErrors()" because the return value of "io.weaviate.client.base.Result.getResult()" is null
2023-10-04 15:06:22.480java.lang.NullPointerException: Cannot invoke "io.weaviate.client.v1.graphql.model.GraphQLResponse.getErrors()" because the return value of "io.weaviate.client.base.Result.getResult()" is null
	at io.kestra.plugin.weaviate.Query.run(Query.java:95)
	at io.kestra.plugin.weaviate.Query.run(Query.java:28)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:662)
```

**Comment by brian-mulier-p** [comment]
As said on slack, this is purely due to putting scheme in host while there is already a dedicated "scheme" property. Should we get rid of that dedicated property and deduce the scheme from the host ?
